/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

Place as a starting conditional in unwanted conversation branches    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (GetTag(GetItemInSlot(INVENTORY_SLOT_HEAD, oPC))!="Unwanted_Conv") return FALSE;

return TRUE;
}

