Rules.RegisterConstants("abilities", "ID")
Rules.RegisterConstants("actions", "Constant")
Rules.RegisterConstants("ambientsound", "Constant")
Rules.RegisterConstants("animations", "ID", nil, "Value", "int")
Rules.RegisterConstants("appearance", "Constant")
Rules.RegisterConstants("area_const", "Constant", nil, "Value", "int")
Rules.RegisterConstants("baseitems", "Constant")
Rules.RegisterConstants("classes", "Constant")
Rules.RegisterConstants("const_object", "Constant", nil, "Value", "int")
Rules.RegisterConstants("const_saves", "Constant", nil, "Value", "int")
Rules.RegisterConstants("creaturesize", "Constant")
Rules.RegisterConstants("disease", "Constant")
Rules.RegisterConstants("door_const", "Constant", nil, "Value", "int")
Rules.RegisterConstants("effects", "Constant")
Rules.RegisterConstants("encdifficulty", "Constant")
Rules.RegisterConstants("feat", "Constant")
Rules.RegisterConstants("hen_familiar", "Constant")
Rules.RegisterConstants("immunities", "Constant")
Rules.RegisterConstants("iprp_alignment", "Constant")
Rules.RegisterConstants("iprp_ammocost", "Constant")
Rules.RegisterConstants("iprp_ammotype", "Constant")
Rules.RegisterConstants("iprp_arcspell", "Constant")
Rules.RegisterConstants("iprp_chargecost", "Constant")
Rules.RegisterConstants("iprp_color", "Constant")
Rules.RegisterConstants("iprp_damagecost", "Constant")
Rules.RegisterConstants("iprp_damagetype", "Constant")
Rules.RegisterConstants("iprp_feats", "Constant")
Rules.RegisterConstants("iprp_immuncost", "Constant")
Rules.RegisterConstants("iprp_immunity", "Constant")
Rules.RegisterConstants("iprp_lightcost", "Constant")
Rules.RegisterConstants("iprp_monstcost", "Constant")
Rules.RegisterConstants("iprp_monsterhit", "Constant")
Rules.RegisterConstants("iprp_onhit", "Constant")
Rules.RegisterConstants("iprp_onhitcost", "Constant")
Rules.RegisterConstants("iprp_onhitdur", "Constant")
Rules.RegisterConstants("iprp_onhitspell", "Constant")
Rules.RegisterConstants("iprp_poison", "Constant")
Rules.RegisterConstants("iprp_protection", "Constant")
Rules.RegisterConstants("iprp_quality", "Constant")
Rules.RegisterConstants("iprp_redcost", "Constant")
Rules.RegisterConstants("iprp_resistcost", "Constant")
Rules.RegisterConstants("iprp_saveelement", "Constant")
Rules.RegisterConstants("iprp_savingthrow", "Constant")
Rules.RegisterConstants("iprp_soakcost", "Constant")
Rules.RegisterConstants("iprp_spells", "Constant")
Rules.RegisterConstants("iprp_spellshl", "Constant")
Rules.RegisterConstants("iprp_srcost", "Constant")
Rules.RegisterConstants("iprp_trapcost", "Constant")
Rules.RegisterConstants("iprp_traps", "Constant")
Rules.RegisterConstants("iprp_visualfx", "Constant")
Rules.RegisterConstants("iprp_soakcost", "Constant")
Rules.RegisterConstants("iprp_weightcost", "Constant")
Rules.RegisterConstants("iprp_weightinc", "Constant")
Rules.RegisterConstants("itempropdef", "Constant")
Rules.RegisterConstants("metamagic", "Constant", nil, "Value", "int")
Rules.RegisterConstants("phenotype", "Constant")
Rules.RegisterConstants("poison", "Constant")
Rules.RegisterConstants("polymorph", "Name")
Rules.RegisterConstants("racialtypes", "Constant")
Rules.RegisterConstants("skills", "Constant")
Rules.RegisterConstants("skyboxes", "Constant")
Rules.RegisterConstants("spells", "Constant")
Rules.RegisterConstants("spellschools", "Constant")
Rules.RegisterConstants("traps", "Constant")
Rules.RegisterConstants("vfx_persistent", "LABEL")
Rules.RegisterConstants("visualeffects", "Label")
