local Srv = require 'ta.server'
local Chat = require 'ta.chat'

local CHAT_SYMBOL_DM = 'dm_'
local CHAT_SYMBOL_ADMIN = 'admin_'
local CHAT_SYMBOL_GENERAL = '!'

Chat.RegisterSymbol(CHAT_SYMBOL_ADMIN, "chat/admin", Srv.VerifyAdmin)
Chat.RegisterSymbol(CHAT_SYMBOL_DM, "chat/dm", Srv.VerifyDM)
Chat.RegisterSymbol(CHAT_SYMBOL_GENERAL, "chat/general")

Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "afk", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "alias", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "anon", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "cdkey", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "convert", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "delete", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "delevel", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "eleswarm", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "follow", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "help", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "ignore", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "level", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "lfg", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "list", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "mode", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "nickname", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "partyfix", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "partyjoin", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "playerinfo", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "playerlist", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "pmshape", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "pvp", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "qb", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "reequip", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "rerender", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "resetdelay", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "sb", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "setdesc", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "skillcheck", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "skilllist", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "summon", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "target", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "time2reset", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "unignore", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "unafk", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "unanon", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "wp", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_GENERAL, "xpbank", "")

Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "align", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "area", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "ban", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "boot", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "create", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "change", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "deity", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "dumpvars", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "fireworks", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "freeze", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "fx", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "getban", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "give", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "guild", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "hide", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "heal", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "help", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "ignore", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "invis", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "invuln", "")
--Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "item", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "jump", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "kill", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "listcommands", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "ness", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "place", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "port", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "rez", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "reset", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "rest", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "reveal", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "set", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "spawn", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "sql", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "stealth", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "store", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "take", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "unban", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "unfreeze", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "uninvis", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "uninvuln", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "var", "")
Chat.RegisterExternalCommand(CHAT_SYMBOL_DM, "vent", "")
